#include "__cf_MR_CIGRE_CONVENCIONAL.h"
#ifndef RTW_HEADER_MR_CIGRE_CONVENCIONAL_acc_types_h_
#define RTW_HEADER_MR_CIGRE_CONVENCIONAL_acc_types_h_
#include "rtwtypes.h"
#include "multiword_types.h"
typedef struct P_Subsystempi2delay_MR_CIGRE_CONVENCIONAL_T_
P_Subsystempi2delay_MR_CIGRE_CONVENCIONAL_T ; typedef struct
P_Subsystem1_MR_CIGRE_CONVENCIONAL_T_ P_Subsystem1_MR_CIGRE_CONVENCIONAL_T ;
typedef struct P_Subsystempi2delay_MR_CIGRE_CONVENCIONAL_h_T_
P_Subsystempi2delay_MR_CIGRE_CONVENCIONAL_h_T ; typedef struct
P_Subsystem1_MR_CIGRE_CONVENCIONAL_l_T_
P_Subsystem1_MR_CIGRE_CONVENCIONAL_l_T ; typedef struct
P_NegSeqComputation_MR_CIGRE_CONVENCIONAL_T_
P_NegSeqComputation_MR_CIGRE_CONVENCIONAL_T ; typedef struct
P_ZeroSeqComputation_MR_CIGRE_CONVENCIONAL_T_
P_ZeroSeqComputation_MR_CIGRE_CONVENCIONAL_T ; typedef struct
P_Subsystempi2delay_MR_CIGRE_CONVENCIONAL_p_T_
P_Subsystempi2delay_MR_CIGRE_CONVENCIONAL_p_T ; typedef struct
P_Subsystem1_MR_CIGRE_CONVENCIONAL_n_T_
P_Subsystem1_MR_CIGRE_CONVENCIONAL_n_T ; typedef struct
P_Subsystempi2delay_MR_CIGRE_CONVENCIONAL_e_T_
P_Subsystempi2delay_MR_CIGRE_CONVENCIONAL_e_T ; typedef struct
P_Subsystem1_MR_CIGRE_CONVENCIONAL_lv_T_
P_Subsystem1_MR_CIGRE_CONVENCIONAL_lv_T ; typedef struct
P_MR_CIGRE_CONVENCIONAL_T_ P_MR_CIGRE_CONVENCIONAL_T ;
#endif
